### ISSUE TITLE
Cannot find zk after installation

### ISSUE THREAD

**Issue by S-N-O-R-L-A-X** [openbuildxyz/mina-zkapp-bootcamp#240]
https://github.com/openbuildxyz/mina-zkapp-bootcamp/discussions/227
![image](https://github.com/user-attachments/assets/aeab8a72-814c-4c7f-ba9d-e0fde7df5fe6)
![image](https://github.com/user-attachments/assets/11dd8178-093c-4d45-accb-f516983139fc)

**Comment by smallfu6** [comment]
@S-N-O-R-L-A-X 我明天找人帮你解决，后面尽量在讨论区提问

**Comment by S-N-O-R-L-A-X** [comment]
> @S-N-O-R-L-A-X 我明天找人帮你解决，后面尽量在讨论区提问

2 days has passed but nobody has reached me.
